name: Without A Map
favicon: null
layout_spectrum: 0.614619261585176
typography_spectrum: 0.8858855795115232
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8477723486721516
  lightness: 0.4214192444924265
  saturation: 0.793544381391257
  rhythmicContrast: 0.35194442770443857
purpose: []
