name: Without A Map
favicon: null
layout_spectrum: 0.49368
typography_spectrum: 0.67397
title: Without A Map
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#2d313a'
    - '#335a95'
    - '#99859e'
    - '#c5bcd1'
  brandStrength: 0.5
  lightness: 0.4214192444924265
  saturation: 0.793544381391257
  rhythmicContrast: 0.35194442770443857
purpose: []
